apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tinyr-ingress
  annotations:
    kubernetes.io/ingress.class: 'gce'
    kubernetes.io/ingress.global-static-ip-name: 'tinyr-static-ip'
    networking.gke.io/managed-certificates: tinyr-certificate
    networking.gke.io/v1beta1.FrontendConfig: tinyr-frontend-config
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: tinyr
                port:
                    number: 8080
  defaultBackend:
    service:
      name: tinyr
      port:
        number: 8080
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: tinyr-frontend-config
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: tinyr-backend-config
spec:
  timeoutSec: 40
  healthCheck:
    type: HTTP
    requestPath: /healthz
    port: 8080
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: tinyr-certificate
spec:
  domains: {{- range .Values.tls.domain }}
    - {{.}}{{- end }}
